### ISSUE TITLE
Homepage carousel not looking good in responsive mode 

### ISSUE THREAD

**Issue by livecodebase** [livecodebase/Explore-Norway#3]
We need  streatch the carousel to full height in order to work with it.

**Comment by PushkaraSharma11** [comment]
Added PR https://github.com/livecodebase/Explore-Norway/pull/5 to fix the issue

**Comment by livecodebase** [comment]
Fixed Now  by PushkaraSharma11 ( https://github.com/PushkaraSharma11 )
