### ISSUE TITLE
Change background images to this

### ISSUE THREAD

**Issue by livecodebase** [livecodebase/Explore-Norway#6]
Change images to this

imgage 1 
https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8dHJhdmVsfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60

image 2
https://images.unsplash.com/photo-1488646953014-85cb44e25828?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8dHJhdmVsfGVufDB8MHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60

image 3
https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8dHJhdmVsfGVufDB8MHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60

**Comment by AmanRana10** [comment]
i can solve this issue @livecodebase

**Comment by PushkaraSharma11** [comment]
https://github.com/livecodebase/Explore-Norway/pull/7 for solving this issue

**Comment by livecodebase** [comment]
Resolved by PushkaraSharma11 https://github.com/PushkaraSharma11
